name: 'Bundlewatch'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: tsc
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
