name: "Bundlephobia""
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: carlesnunez/check-my-bundlephobia@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-dev-dependencies: true